# Since Function
Topics: Broadcasting, Fancy Indexing

The [sinc function](https://en.wikipedia.org/wiki/Sinc_function) is defined by: 

$$ \large sinc(r) = \frac{sin(r)}{r} $$


1. Create a Cartesian x,y grid by defining `x` and `y` as arrays of evenly spaced numbers over the interval `[-15, 15]`. Each of these arrays should have `101` numbers.

2. Reshape the `y` array into a "column" vector by increasing the dimensionality using array slicing and `newaxis`.

3. Create an array of `r` that corresponds to the following equation:

$$ \large r = \sqrt{x^2 + y^2} $$


4. Calculate the sinc function of `r`.

5. Replace any location in `sinc` where `r` is `0` with `1.0`.


## Bonus
6. Plot the result of the sinc function using `matplotlib`'s `plt.imshow` function.

In [1]:
%matplotlib inline
from numpy import linspace, sin, sqrt, newaxis
import matplotlib.pyplot as plt

1. Create a Cartesian x,y grid by defining `x` and `y` as arrays of evenly spaced numbers over the interval `[-15, 15]`. Each of these arrays should have `101` numbers.

In [11]:
x = linspace(-15, 15, 101)
y = linspace(-15, 15, 101)

2. Reshape the y array into a "column" vector by increasing the dimensionality using array slicing and newaxis.

In [12]:
y = y[:, newaxis]
y

array([[-15. ],
       [-14.7],
       [-14.4],
       [-14.1],
       [-13.8],
       [-13.5],
       [-13.2],
       [-12.9],
       [-12.6],
       [-12.3],
       [-12. ],
       [-11.7],
       [-11.4],
       [-11.1],
       [-10.8],
       [-10.5],
       [-10.2],
       [ -9.9],
       [ -9.6],
       [ -9.3],
       [ -9. ],
       [ -8.7],
       [ -8.4],
       [ -8.1],
       [ -7.8],
       [ -7.5],
       [ -7.2],
       [ -6.9],
       [ -6.6],
       [ -6.3],
       [ -6. ],
       [ -5.7],
       [ -5.4],
       [ -5.1],
       [ -4.8],
       [ -4.5],
       [ -4.2],
       [ -3.9],
       [ -3.6],
       [ -3.3],
       [ -3. ],
       [ -2.7],
       [ -2.4],
       [ -2.1],
       [ -1.8],
       [ -1.5],
       [ -1.2],
       [ -0.9],
       [ -0.6],
       [ -0.3],
       [  0. ],
       [  0.3],
       [  0.6],
       [  0.9],
       [  1.2],
       [  1.5],
       [  1.8],
       [  2.1],
       [  2.4],
       [  2.7],
       [  3. ],
       [  3.3],
       [

3. Create an array of `r` that corresponds to the following equation:

$$ \large r = \sqrt{x^2 + y^2} $$

In [13]:
r = sqrt(x**2 + y**2)
r

array([[21.21320344, 21.00214275, 20.79326814, ..., 20.79326814,
        21.00214275, 21.21320344],
       [21.00214275, 20.78893937, 20.57790077, ..., 20.57790077,
        20.78893937, 21.00214275],
       [20.79326814, 20.57790077, 20.3646753 , ..., 20.3646753 ,
        20.57790077, 20.79326814],
       ...,
       [20.79326814, 20.57790077, 20.3646753 , ..., 20.3646753 ,
        20.57790077, 20.79326814],
       [21.00214275, 20.78893937, 20.57790077, ..., 20.57790077,
        20.78893937, 21.00214275],
       [21.21320344, 21.00214275, 20.79326814, ..., 20.79326814,
        21.00214275, 21.21320344]])

4. Calculate the sinc function of `r`

In [14]:
sinc = sin(r)/r
sinc

/tmp/ipykernel_16081/221344926.py:1: RuntimeWarning: invalid value encountered in true_divide
  sinc = sin(r)/r


array([[0.03308398, 0.03978071, 0.04478704, ..., 0.04478704, 0.03978071,
        0.03308398],
       [0.03978071, 0.04487181, 0.04799396, ..., 0.04799396, 0.04487181,
        0.03978071],
       [0.04478704, 0.04799396, 0.04902855, ..., 0.04902855, 0.04799396,
        0.04478704],
       ...,
       [0.04478704, 0.04799396, 0.04902855, ..., 0.04902855, 0.04799396,
        0.04478704],
       [0.03978071, 0.04487181, 0.04799396, ..., 0.04799396, 0.04487181,
        0.03978071],
       [0.03308398, 0.03978071, 0.04478704, ..., 0.04478704, 0.03978071,
        0.03308398]])

5. Replace any location in `sinc` where `r` is `0` with `1.0`.

In [17]:
sinc[r == 0] = 1.0
sinc

array([[0.03308398, 0.03978071, 0.04478704, ..., 0.04478704, 0.03978071,
        0.03308398],
       [0.03978071, 0.04487181, 0.04799396, ..., 0.04799396, 0.04487181,
        0.03978071],
       [0.04478704, 0.04799396, 0.04902855, ..., 0.04902855, 0.04799396,
        0.04478704],
       ...,
       [0.04478704, 0.04799396, 0.04902855, ..., 0.04902855, 0.04799396,
        0.04478704],
       [0.03978071, 0.04487181, 0.04799396, ..., 0.04799396, 0.04487181,
        0.03978071],
       [0.03308398, 0.03978071, 0.04478704, ..., 0.04478704, 0.03978071,
        0.03308398]])

## Bonus
6. Plot the result of the sinc function using `matplotlib`'s `plt.imshow` function.

In [ ]:
### Will do after covering matplotlib ###