# Load Array from Text File

0. In a clean notebook cell, type:

        In [ ]: loadtxt?

   to see the options on how to use the `loadtxt` command.


1. Use `loadtxt` to load in a 2D array of floating point values from `'float_data.txt'`.
   The data in the file looks like:

        1 2 3 4
        5 6 7 8

   The resulting data should be a 2x4 array of floating point values.


2. In the second example, the file `'float_data_with_header.txt'` has
   strings as column names in the first row:

        c1 c2 c3 c4
         1  2  3  4
         5  6  7  8

   Ignore these column names, and read the remainder of the data into
   a 2D array.

## Bonus


3. A third example is more involved. It contains comments in multiple
   locations, uses multiple formats, and includes a useless column to
   skip:

    -- THIS IS THE BEGINNING OF THE FILE --  
    % This is a more complex file to read!

    % Day,  Month,  Year, Useless Col, Avg Power
       01,     01,  2000,      ad766,         30
       02,     01,  2000,       t873,         41
    % we don't have Jan 03rd!
       04,     01,  2000,       r441,         55
       05,     01,  2000,       s345,         78
       06,     01,  2000,       x273,        134 % that day was crazy
       07,     01,  2000,       x355,         42

    %-- THIS IS THE END OF THE FILE --


In [2]:
from numpy import loadtxt

0. Use the command `loadtxt?` below to see the options on how to use the `loadtxt` command.

In [3]:
loadtxt?

Signature:
loadtxt(
    fname,
    dtype=<class 'float'>,
    comments='#',
    delimiter=None,
    converters=None,
    skiprows=0,
    usecols=None,
    unpack=False,
    ndmin=0,
    encoding='bytes',
    max_rows=None,
    *,
    like=None,
)
Docstring:
Load data from a text file.

Each row in the text file must have the same number of values.

Parameters
----------
fname : file, str, or pathlib.Path
    File, filename, or generator to read.  If the filename extension is
    ``.gz`` or ``.bz2``, the file is first decompressed. Note that
    generators should return byte strings.
dtype : data-type, optional
    Data-type of the resulting array; default: float.  If this is a
    structured data-type, the resulting array will be 1-dimensional, and
    each row will be interpreted as an element of the array.  In this
    case, the number of columns used must match the number of fields in
    the data-type.
comments : str or sequence of str, optional
    The characters or list of charac

1. Use `loadtxt` to load in a 2D array of floating point values from `'float_data.txt'`.
   The data in the file looks like:

        1 2 3 4
        5 6 7 8

   The resulting data should be a 2x4 array of floating point values.

In [4]:
# Simple example loading a 2x4 array of floats from a file
ary1 = loadtxt('float_data.txt')

print('example 1:')
print(ary1)

example 1:
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


2. In the second example, the file `'float_data_with_header.txt'` has
   strings as column names in the first row:

        c1 c2 c3 c4
         1  2  3  4
         5  6  7  8

   Ignore these column names, and read the remainder of the data into
   a 2D array.

In [11]:
# Same example, but skipping the first row of column headers
ary2 = loadtxt('float_data_with_header.txt', skiprows=1)

print('example 2:')
print(ary2)

example 2:
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


## Bonus


3. A third example is more involved. It contains comments in multiple
   locations, uses multiple formats, and includes a useless column to
   skip:

    -- THIS IS THE BEGINNING OF THE FILE --  
    % This is a more complex file to read!

    % Day,  Month,  Year, Useless Col, Avg Power
       01,     01,  2000,      ad766,         30
       02,     01,  2000,       t873,         41
    % we don't have Jan 03rd!
       04,     01,  2000,       r441,         55
       05,     01,  2000,       s345,         78
       06,     01,  2000,       x273,        134 % that day was crazy
       07,     01,  2000,       x355,         42

    %-- THIS IS THE END OF THE FILE --

In [16]:
# More complex example with comments and columns to skip
ary3 = loadtxt('complex_data_file.txt', delimiter=",", skiprows=1, usecols=(0,1,2,4), comments="%", dtype=int)

print('example 3:')
print(ary3)

example 3:
[[   1    1 2000   30]
 [   2    1 2000   41]
 [   4    1 2000   55]
 [   5    1 2000   78]
 [   6    1 2000  134]
 [   7    1 2000   42]]
